name: Build
on: push
jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      packages: read

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Checkout base repo
        uses: actions/checkout@v5
        with:
          repository: edave64/Doki-Doki-Dialog-Generator
          ref: main
          path: main

      - name: Checkout asset repo
        uses: actions/checkout@v5
        with:
          repository: edave64/dddg-assets
          ref: gh-pages
          path: assets

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - shell: bash
        run: echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - shell: bash
        run: npm install && npm run build:electron
        working-directory: main

      - shell: bash
        run: |
          cp -r ./main/dist ./dddgWeb
          rm -rf ./dddgWeb/assets
          cp -r ./assets/v2/** ./dddgWeb/
          rm -f ./dddgWeb/assets/**/*.lq.webp ./dddgWeb/assets/**/*.png
          rm -rf main
          rm -rf assets

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - shell: bash
        run: ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist ${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.exe.blockmap
            dist/*.dmg
            dist/*.dmg.blockmap
            dist/*.AppImage
            dist/latest*.yml
